from .user_model import User
from .doctor_model import Doctor
from .nurse_model import Nurse
from .patient_model import Patient
from .examination_model import Examination
from .reservation_model import Reservation
from .visit_model import Visit
from .prescription_model import Prescription
from .referral_model import Referral
from .disease_model import Disease
from .diagnosis_model import Diagnosis
