from .diagnosis_model import Diagnosis
from .disease_model import Disease
from .doctor_model import Doctor
from .examination_model import Examination
from .nurse_model import Nurse
from .patient_model import Patient
from .prescription_model import Prescription
from .referral_model import Referral
from .reservation_model import Reservation
from .schedule_model import Schedule
from .user_model import User
from .visit_model import Visit
