"""add_glassmorphism_settings

Revision ID: 989dd44f3094
Revises: 
Create Date: 2025-12-27 14:25:36.344422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '989dd44f3094'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('bg_opacity', sa.Float(), nullable=True))
    op.add_column('user_settings', sa.Column('bg_blur', sa.Integer(), nullable=True))
    op.add_column('user_settings', sa.Column('bg_brightness', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'bg_brightness')
    op.drop_column('user_settings', 'bg_blur')
    op.drop_column('user_settings', 'bg_opacity')
    # ### end Alembic commands ###
